### ISSUE TITLE
Is it possible to ingest logs for each invoke synchronously?

### ISSUE THREAD

**Issue by iamjaredwalters** [lumigo-io/lambda-log-shipper#11]
I've noticed that logs for an invoke aren't always stored in s3 and sometimes logs are stored for previous invocations. After digging through some docs and code examples I found this mentioned:

> As the example is an asynchronous system, logs for one invoke may be processed during the next invocation. Logs for the last invoke may be processed during the SHUTDOWN event.

Any idea if there is a way to avoid this situation and reliably store logs per invocation using lambda extensions and the log API?

**Comment by saartochner** [comment]
Hi Jared,
This is possible to store logs synchronously for each invocation using the extensions and logs API.
Unfortunately, this is currently a missing feature in this project.

I'm inviting you to contribute to this project. 
The change is rather small: add a blocker function to `LogManager`, and invoke it in the `extension_loop` instead of the nonblocking `send_batch_if_needed`. This function should block the extension from finishing until it will send the final log of the invocation.

BTW, the logs shouldn't be missing. They should be digested after a small delay, bound by a few minutes. 
Do you see something else?

**Comment by iamjaredwalters** [comment]
> The change is rather small: add a blocker function to LogManager, and invoke it in the extension_loop instead of the nonblocking send_batch_if_needed

Interesting. I've re-thought my approach and may not need this functionality but should I decide to head this direction I will happily open up a PR. Im trying to wrap my head around what log files this approach would produce. Would it be one log file for the invocation phase and one for the shutdown phase?

> BTW, the logs shouldn't be missing. They should be digested after a small delay, bound by a few minutes.
Logs appear to be showing as described here. I'll keep an eye out and let you know if I see otherwise.

Appreciate the help ❤️

**Comment by saartochner** [comment]
I'm happy to see that you find it helpful :-)

It should be one log file per batch, and each batch is defined by the minimum between the configured size and time (default 1KB data and 1 minute time)
